
import { GoogleGenAI } from "@google/genai";

if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable is not set.");
}

const isBrowser = typeof window !== 'undefined';
const ai = new GoogleGenAI({ 
    apiKey: process.env.API_KEY, 
    httpOptions: isBrowser ? { baseUrl: window.location.origin + '/api/gemini' } : undefined 
});

const fileToGenerativePart = async (file: File) => {
  const base64EncodedDataPromise = new Promise<string>((resolve) => {
    const reader = new FileReader();
    reader.onloadend = () => {
        if (typeof reader.result === 'string') {
            resolve(reader.result.split(',')[1]);
        } else {
            resolve(''); // Should not happen with readAsDataURL
        }
    };
    reader.readAsDataURL(file);
  });
  return {
    inlineData: { data: await base64EncodedDataPromise, mimeType: file.type },
  };
};

export const describeImageForEmoji = async (imageFile: File): Promise<string> => {
    try {
        const imagePart = await fileToGenerativePart(imageFile);
        const textPart = {
            text: "Analyze the main subject in this image. Describe it in a short, fun, and expressive phrase perfect for generating a cartoon emoji sticker. For example: 'A happy Corgi dog wearing sunglasses' or 'A mischievous cat peeking from behind a sofa'."
        };

        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: { parts: [textPart, imagePart] }
        });

        if (!response.text) {
            throw new Error("No description was returned by the model.");
        }
        return response.text;
    } catch (error) {
        console.error("Error describing image:", error);
        const msg = error instanceof Error ? error.message : "Unknown error";
        throw new Error(`Could not get a description from the image: ${msg}`);
    }
};

export const generateEmojiFromDescription = async (description: string): Promise<string> => {
    try {
        const prompt = `A cute, expressive cartoon emoji sticker of ${description}. The emoji should have a thick white outline and a transparent background, sticker style, high resolution, vibrant colors.`;

        const response = await ai.models.generateImages({
            model: 'imagen-4.0-generate-001',
            prompt: prompt,
            config: {
                numberOfImages: 1,
                outputMimeType: 'image/png',
                aspectRatio: '1:1',
            },
        });

        const imageBytes = response.generatedImages?.[0]?.image?.imageBytes;
        if (imageBytes) {
            return imageBytes;
        } else {
            throw new Error("No image was generated by the API.");
        }
    } catch (error) {
        console.error("Error generating emoji:", error);
        const msg = error instanceof Error ? error.message : "Unknown error";
        throw new Error(`Could not generate the emoji image: ${msg}`);
    }
};

export const generateEmojiFromPollinations = async (description: string): Promise<string> => {
    try {
        const prompt = encodeURIComponent(`A cute, expressive cartoon emoji sticker of ${description}. The emoji should have a thick white outline and a transparent background, sticker style, high resolution, vibrant colors.`);
        const baseUrl = isBrowser ? window.location.origin + '/api/pollinations' : 'https://image.pollinations.ai';
        const url = `${baseUrl}/prompt/${prompt}?width=1024&height=1024&nologo=true&private=true&enhance=false`;

        const response = await fetch(url);
        if (!response.ok) {
            throw new Error(`Failed to fetch image from Pollinations: status ${response.status} ${response.statusText || ''}`);
        }

        const blob = await response.blob();
        const reader = new FileReader();
        const base64EncodedDataPromise = new Promise<string>((resolve, reject) => {
            reader.onloadend = () => {
                if (typeof reader.result === 'string') {
                    resolve(reader.result.split(',')[1]);
                } else {
                    resolve('');
                }
            };
            reader.onerror = () => reject(new Error("Failed to read image data."));
            reader.readAsDataURL(blob);
        });

        return await base64EncodedDataPromise;
    } catch (error) {
        console.error("Error generating emoji via Pollinations:", error);
        const msg = error instanceof Error ? error.message : "Unknown error";
        throw new Error(`Could not generate the emoji image via Pollinations: ${msg}`);
    }
};
