
import { GoogleGenAI } from "@google/genai";

if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable is not set.");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

const fileToGenerativePart = async (file: File) => {
  const base64EncodedDataPromise = new Promise<string>((resolve) => {
    const reader = new FileReader();
    reader.onloadend = () => {
        if (typeof reader.result === 'string') {
            resolve(reader.result.split(',')[1]);
        } else {
            resolve(''); // Should not happen with readAsDataURL
        }
    };
    reader.readAsDataURL(file);
  });
  return {
    inlineData: { data: await base64EncodedDataPromise, mimeType: file.type },
  };
};

export const describeImageForEmoji = async (imageFile: File): Promise<string> => {
    try {
        const imagePart = await fileToGenerativePart(imageFile);
        const textPart = {
            text: "Analyze the main subject in this image. Describe it in a short, fun, and expressive phrase perfect for generating a cartoon emoji sticker. For example: 'A happy Corgi dog wearing sunglasses' or 'A mischievous cat peeking from behind a sofa'."
        };

        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: { parts: [textPart, imagePart] }
        });

        return response.text;
    } catch (error) {
        console.error("Error describing image:", error);
        throw new Error("Could not get a description from the image.");
    }
};

export const generateEmojiFromDescription = async (description: string): Promise<string> => {
    try {
        const prompt = `A cute, expressive cartoon emoji sticker of ${description}. The emoji should have a thick white outline and a transparent background, sticker style, high resolution, vibrant colors.`;

        const response = await ai.models.generateImages({
            model: 'imagen-3.0-generate-002',
            prompt: prompt,
            config: {
                numberOfImages: 1,
                outputMimeType: 'image/png',
                aspectRatio: '1:1',
            },
        });

        if (response.generatedImages && response.generatedImages.length > 0 && response.generatedImages[0].image.imageBytes) {
            return response.generatedImages[0].image.imageBytes;
        } else {
            throw new Error("No image was generated by the API.");
        }
    } catch (error) {
        console.error("Error generating emoji:", error);
        throw new Error("Could not generate the emoji image.");
    }
};
